spring:
  datasource:
    url: jdbc:mysql://localhost:3308/pass_local
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: ture
        ddl-auto: create
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    org.springframework: info
    org.example: debug
debug: false